version: '3'
services:
   api:
      container_name: easter-api
      restart: always
      build: .
      ports:
         - '5000:4000'
      depends_on:
         - postgres
      environment: 
         DATABASE_URL: mongodb://database:27018
      links:
         - postgres:postgres
   postgres:
      container_name: easter-postgres
      restart: always
      image: postgres:13-alpine
      ports:
         - 1234:1234
      environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: password