name: Main

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
      AUTH_ACCESS_TOKEN_SECRET: ${{ secrets.AUTH_ACCESS_TOKEN_SECRET }}
      MAIL_CLIENT_ID: ${{ secrets.MAIL_CLIENT_ID }}
      MAIL_CLIENT_SECRET: ${{ secrets.MAIL_CLIENT_SECRET }}
      MAIL_REFRESH_TOKEN: ${{ secrets.MAIL_REFRESH_TOKEN }}
      MAIL_USER: ${{ secrets.MAIL_USER }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Check for lint errors
      run: npm run lint