name: Main

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      APP_PREFIX: ${{ secrets.APP_PREFIX }}
      AUTH_ACCESS_TOKEN_SECRET: ${{ secrets.AUTH_ACCESS_TOKEN_SECRET }}
      DATABASE_URL: "postgresql://root:password@localhost:5432/easter_api?schema=public"
      MAIL_CLIENT_ID: ${{ secrets.MAIL_CLIENT_ID }}
      MAIL_CLIENT_SECRET: ${{ secrets.MAIL_CLIENT_SECRET }}
      MAIL_REFRESH_TOKEN: ${{ secrets.MAIL_REFRESH_TOKEN }}
      MAIL_USER: ${{ secrets.MAIL_USER }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn ci
      
    - name: Apply migrations
      run: yarn prisma:migrate:dev

    - name: Build application
      run: yarn build

    - name: Run unit tests
      run: yarn test:unit

    - name: Run e2e tests
      run: yarn test:e2e
      
    - name: Check for lint errors
      run: yarn lint